#! /bin/bash

#   Add service file to runlevel directory

/bin/cp /etc/init.d/powertop /etc/runlevels/default || true

#   Add service to runlevel

rc-update add powertop default

#   Update services list

rc-update -u
